### ISSUE TITLE
Very long installation process

### ISSUE THREAD

**Issue by saidbakr** [medhatdawoud/vuejs-playground#3]
I have cloned the project and I did the following steps from the `vuejs-playground` folder:
 1. `npm install vue`
 2. `npm install webpack`
 3. `npm install babel-core babel-loader`
 4. `npm install babel-cli babel-preset-es2015`
 5. `npm install vue-template-compiler`

Before each step I have run `npm run build` to checkout the missing modules. Finally I ended with:
```
ERROR in ./src/App/index.vue
Module not found: Error: Can't resolve 'css-loader' in '/home/saidbakr/Desktop/py4e/vuejs-playground/src/App'
 @ ./src/App/index.vue 4:2-193
 @ ./src/main.js
```
Finally `npm install css-loader` make it run.

Additionally, the script tag to the src in `index.html` has no valid path on the file system. i.e you could not able to run it from the local web browser. To do the prefixed slash should be removed to be:
```
<script src="build/main.js"></script>
```
However, I have used `php -S localhost:8000` at the project root folder to serve it

**Comment by medhatdawoud** [comment]
This repo was long time ago, feel free to create a PR to make it easier for other people to use

**Comment by saidbakr** [comment]
@medhatdawoud I noticed that almost all dependencies are found in [`package.json`](https://github.com/medhatdawoud/vuejs-playground/blob/master/package.json) but I could not able to understand why `npm run build` does not able to follow up them from it?!

**Comment by AhmedHelalAhmed** [comment]
Hello,

To run the project I run 
```
npm install
npm run start
npm run watch
```
Finally 
`npm run build`
check that

[screen](https://i.imgur.com/ETsvQE3.png)

**Comment by AhmedHelalAhmed** [comment]
@saidbakr
 please check my review and update your pull request 
https://github.com/medhatdawoud/vuejs-playground/pull/4#pullrequestreview-377409792

**Comment by saidbakr** [comment]
[Fixed](https://github.com/medhatdawoud/vuejs-playground/pull/5)
